### WORKING Refresh Token Test
POST http://localhost:3052/v1/api/product/create-product
Content-Type: application/json
x-api-key: 5961ba7ba4620ba62fc0acde6a9f1ef8f46cecff45bc5835809eee69e071a2aa
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODkyYzVlODVmMTEzMDk4MDllMTUzNTciLCJlbWFpbCI6InRlc3Rwb3N0bWFuQGdtYWlsLmNvbSIsImlhdCI6MTc1NDk2ODg4NiwiZXhwIjoxNzU1MTQxNjg2fQ.Azg8IgsATELFQ7D3RagUKFnevjTCeHkBz1cgqSJtzzqukS3okZNbgo8c4fi8fzG2w-e7N_zjfyiAXs4ya3PBOG-aRaMm2FBVwYjPHU0kTN4EPpDvktq7b5LOqN1ydqBGO4TlX55k8jADWbqkdocgB1O1PnuFfGK5TNKSKF8XseoC4Z6joQS7DlJrEa3VVL3lPYzHF52xFOieBojO85R7R9ONOEu-DvVYO0-5P1docl4ocDhY9ve7MBIR5QS5ISkqRGMPqqoddp5wi64bDnQOcRXV61pa0LcF2TbVKQsXm4Y1kWPiQ_CdC-iY2Abd08fvXq5rsVR16UzT8eq1T9uS4LnVvzcWhUFfQJ61dD74PPLSkD2mEahX30trsnlWWlHhUaZd8npmjSQtLTKIP78NF4OFCHxNXJp5nHT3Paahbhfw97aiZYs_wLVSB6O5N7Z8Z-nx5e3qo8J-QQbntWTcvF7NNHwUoKGKpiJoT9suGjODXnVQ3p2fRoyG_CxPbLJV22eQsuPW5M3xv8LT46CHp8ZA6Kq9xDAGIfXK8eo5o7Ikl6DE2PL109hVBnLZfEDDor8fPgFSWsqvP5HVVECoEawHKMRoI3dohHsA7GkFKtvpQogdl0-CUqwWm4c20YEh85XVOO5fO4CM4KNXMATMJqv0BBqsjIBBBYF7hHNVzqg
x-client-id: 6892c5e85f11309809e15357

{
    "product_name": "OPPO X200 Ultra",
    "product_description": "Latest model Oppo",
    "product_type": "Electronics",
    "product_thumb": "https://example.com/new-jeans-thumb.jpg",
    "product_price": 500,
    "product_quantity": 10,
    "product_attributes": {
        "brand": "OPPO",
        "model": "X200 Ultra",
        "color": "white"
    }
}
